# PostgreSQL Database Configuration
db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://localhost:5432/giasutot
db.username=postgres
<<<<<<< HEAD
db.password=123456
=======
db.password=1
>>>>>>> origin/main
